version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/src" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      nuget-all:
        patterns:
          - "*"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/infra" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      terraform-all:
        patterns:
          - "*"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/src/API" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      docker-all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      gha-all:
        patterns:
          - "*"
